/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.wenvusage;

public class App {
    public String getGreeting() {
        return "Ciao Mondo Con La Prima Lettera Maiuscola!v2";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
